'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Input} from '@/components/ui/input';
import {login,logout,acceptInvite,recoverPassword,requestPasswordRecovery,handleAuthCallback} from '@netlify/identity';
export default function NetlifyLogin(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[mode,setMode]=useState<'login'|'invite'|'recovery'>('login'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));const invite=params.get('invite_token'),recovery=params.get('recovery_token');if(invite||recovery){setMode(invite?'invite':'recovery');setToken(invite||recovery||'');history.replaceState(null,'','/admin')}else if(params.has('confirmation_token')||params.has('access_token')){void handleAuthCallback().then(()=>location.replace('/admin')).catch(()=>setMessage('验证链接无效或已过期，请重新获取。'))}},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(mode==='invite')await acceptInvite(token,password);else if(mode==='recovery')await recoverPassword(token,password);else await login(email,password);const check=await fetch('/api/admin/content');if(!check.ok){await logout();throw Error('当前账号没有管理权限，请使用网站管理员账号。')}location.replace('/admin')}catch(e){setMessage(e instanceof Error?e.message:'登录失败，请重试')}finally{setBusy(false)}}
 async function recover(){if(!email){setMessage('请先填写管理员邮箱。');return}setBusy(true);try{await requestPasswordRecovery(email);setMessage('若邮箱已注册，重置链接会发送到该邮箱。')}catch{setMessage('暂时无法发送，请稍后重试。')}finally{setBusy(false)}}
 return <main className="cms cms-login"><span className="cms-kicker">PORTFOLIO / STUDIO</span><h1>{mode==='login'?'登录内容管理':mode==='invite'?'设置管理员密码':'重置密码'}</h1><p>管理你的作品、简历与首页视觉。</p><form onSubmit={submit} style={{width:'100%',maxWidth:380,textAlign:'left'}}>{mode==='login'&&<label className="cms-field" htmlFor="admin-email"><span>管理员邮箱</span><Input id="admin-email" autoComplete="username" type="email" value={email} onChange={e=>setEmail(e.target.value)} required disabled={busy}/></label>}<label className="cms-field" htmlFor="admin-password"><span>密码</span><Input id="admin-password" type="password" minLength={mode==='login'?1:12} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} required disabled={busy}/></label><button type="submit" className="cms-primary" disabled={busy}>{busy?'正在处理…':mode==='login'?'登录 →':'设置密码并登录 →'}</button>{mode==='login'&&<button type="button" className="cms-secondary" style={{marginLeft:12}} disabled={busy} onClick={()=>{void recover()}}>忘记密码</button>}{message&&<p role="status" className="cms-note" style={{marginTop:18}}>{message}</p>}</form><a href="/">返回作品集</a></main>
}
