'use client';
import { useEffect, useState } from 'react';
const works = [ ['Forma Studio','Art direction / Identity','2026'], ['Between Spaces','Editorial / Digital','2025'], ['Objects of Tomorrow','Branding / Strategy','2025'] ];
export default function Home() {
 const [time,setTime]=useState('');
 useEffect(()=>{const update=()=>setTime(new Date().toLocaleTimeString('en-GB',{timeZone:'Asia/Shanghai'}));update();const id=setInterval(update,1000);return ()=>clearInterval(id)},[]);
 return <main id="home">
 <header className="nav"><a href="#home" className="logo">NOVA®</a><nav aria-label="Main navigation"><a href="#home">Home</a><a href="#works">Works <sup>[03]</sup></a><a href="#about">About</a><a href="#contact">Contact ↗</a></nav><div className="location"><span>{time || '—'} GMT+8</span><span>Shanghai, China</span></div></header>
 <section className="hero" aria-label="Nova creative portfolio"><div className="eyebrow"><span>Independent designer & art director</span><span>Portfolio — 2026</span></div><h1>NOVA<span className="star">✳</span></h1><div className="hero-bottom"><p>Ideas into identities.<br/>Thoughts into experiences.</p><span className="availability"><i/> Available for selected projects</span><a href="#works">[ Explore works ↓ ]</a></div><div className="hero-gallery"><a href="#project-1" className="hero-image first"><img src="/images/work-01.png" alt="Experimental editorial project"/><span>01 / FORMA STUDIO ↗</span></a><a href="#project-2" className="hero-image second"><img src="/images/work-02.png" alt="Contemporary digital design project"/><span>02 / BETWEEN SPACES ↗</span></a><a href="#project-3" className="hero-image third"><img src="/images/work-03.png" alt="Brand identity project"/><span>03 / OBJECTS OF TOMORROW ↗</span></a></div><div className="caption"><span>Latest work</span><span>Vol. 01 — 03</span><span>Scroll to discover ↓</span></div></section>
 <section id="works" className="section"><div className="section-head"><h2>Selected work<sup>[03]</sup></h2><span>2025 — 2026</span></div><div className="projects">{works.map(([name,type,year],i)=><article className="project" id={`project-${i+1}`} key={name}><div className="project-label"><span>00{i+1}</span><h3>{name}</h3><span>{type}</span><span>{year}</span></div><div className="project-image"><img src={`/images/work-0${i+1}.png`} alt={`${name} — example portfolio artwork`} loading="lazy"/></div><p className="project-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. A study in form, feeling, and the spaces in between.</p></article>)}</div></section>
 <section id="about" className="about section"><div className="eyebrow"><span>A little about me</span><span>Strategy meets instinct</span></div><h2>I make things<br/>mean <em>something.</em></h2><div className="about-copy"><span>[ NOVA / DESIGNER ]</span><div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. I work at the intersection of visual identities and digital experiences, turning a little curiosity into something unexpected.</p><p>Based somewhere between a good idea and its next iteration. Open to thoughtful collaborations, new perspectives, and ambitious little things.</p></div></div><div className="services"><span>What I do</span>{['Art direction','Brand identity','Digital experiences','Editorial design'].map((s,i)=><div key={s}><span>0{i+1}</span><h3>{s}</h3><span>↗</span></div>)}</div></section>
 <footer id="contact"><div className="eyebrow"><span>Have something in mind?</span><span>Let’s make it happen.</span></div><a className="contact-link" href="mailto:hello@example.com">LET’S TALK <span>↗</span></a><div className="footer-bottom"><span>© 2026 NOVA</span><span>hello@example.com · Demo contact</span><a href="#home">Back to top ↑</a></div></footer>
 </main>
}
